type GENRE = {
  name: string;
  route: string;
};

export const ALL_GENRE: Array<GENRE> = [
  { name: "Action", route: "action" },
  { name: "Adult", route: "adult" },
  { name: "Adventure", route: "adventure" },
  { name: "Anime & Comics", route: "anime-&-comics" },
  { name: "Comedy", route: "comedy" },
  { name: "Drama", route: "drama" },
  { name: "Eastern", route: "eastern" },
  { name: "Ecchi", route: "ecchi" },
  { name: "Fanfiction", route: "fanfiction" },
  { name: "Fantasy", route: "fantasy" },
  { name: "Game", route: "game" },
  { name: "Gender Bender", route: "gender-bender" },
  { name: "Harem", route: "harem" },
  { name: "Historical", route: "historical" },
  { name: "Horror", route: "horror" },
  { name: "Isekai", route: "isekai" },
  { name: "Josei", route: "josei" },
  { name: "Lgbt+", route: "lgbt+" },
  { name: "Litrpg", route: "litrpg" },
  { name: "Magic", route: "magic" },
  { name: "Magic Realism", route: "magic-realism" },
  { name: "Martial Arts", route: "martial-arts" },
  { name: "Mature", route: "mature" },
  { name: "Mecha", route: "mecha" },
  { name: "Modern Life", route: "modern-life" },
  { name: "Mystery", route: "mystery" },
  { name: "Other", route: "other" },
  { name: "Psychological", route: "psychological" },
  { name: "Reincarnation", route: "reincarnation" },
  { name: "Romance", route: "romance" },
  { name: "School Life", route: "school-life" },
  { name: "Sci-Fi", route: "sci-fi" },
  { name: "Slice Of Life", route: "slice-of-life" },
  { name: "Smut", route: "smut" },
  { name: "Sports", route: "sports" },
  { name: "Supernatural", route: "supernatural" },
  { name: "System", route: "system" },
  { name: "Tragedy", route: "tragedy" },
  { name: "Urban", route: "urban" },
  { name: "Urban Life", route: "urban-life" },
  { name: "Video Games", route: "video-games" },
  { name: "Wuxia", route: "wuxia" },
  { name: "Xianxia", route: "xianxia" },
];
